### ISSUE TITLE
Washington, DC

### ISSUE THREAD

**Issue by murphyjoe** [javierarce/spotimap#1]
I added a bunch of songs about Washington, DC - hope it's OK to put them all in one issue. (If multiple issues are better, let me know.)

"Banned in DC" by Bad Brains
https://play.spotify.com/track/6MYusHmom4vpQN4qGyHl0h

"The Bourgeois Blues" by Lead Belly
https://play.spotify.com/track/0D1Nnj6F6NCeSwg9Er2S2S

"Chocolate City" by Parliament
https://play.spotify.com/track/0tkokbqEygQIxlQ8oap3KN

"Christmas Eve in Washington" by Maura Sullivan
https://play.spotify.com/track/3Q0vBlBA7OfygRJrCBGnSP

"The District Sleeps Alone Tonight" by The Postal Service
https://play.spotify.com/track/5Bf5C7RkyXTqE1h3Q8KZJ7

"Washington, D.C." by The Magnetic Fields
https://play.spotify.com/track/3Qa8X1dC8Tgs4QtGobmvCU

"The Washington Post March" by John Philip Sousa
https://play.spotify.com/track/4rwcwWufNLwNDU7VmyuRr7

**Comment by javierarce** [comment]
Thanks a lot, @murphyjoe, I've just added the songs: http://javierarce.com/spotimap/?city=Washington

Sorry it took me so long to add them!
