### ISSUE TITLE
Genoa (Italy)

### ISSUE THREAD

**Issue by sabas** [javierarce/spotimap#2]
I added two songs (https://en.wikipedia.org/w/index.php?title=List_of_songs_about_cities&diff=650607765&oldid=650605508)

Genova per noi - Paolo Conte
https://play.spotify.com/album/1sRrtH1UVQNfGjAgqXKE5F/5nKwVYrMD3ETJ0T62uVw5k

Ma se ghe penso (traditional song in genoese)
https://play.spotify.com/album/1lsVsN3WMV2YB3nchzhwXJ/3TQL5txOmtnOqcpvZJ59Lz

**Comment by javierarce** [comment]
Thanks a lot, @sabas!

Here are the songs: http://javierarce.com/spotimap/?city=Genoa

**Comment by sabas** [comment]
Thanks!
